version: "3.1"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/config.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana_data:/var/lib/grafana
    links:
      - prometheus
  node-exporter:
    image: prom/node-exporter
    container_name: prometheus-node-exporter
    ports:
        - '9100:9100'
  example-web-api:
    build: 
      context: ./example-web-api
    container_name: example-web-api
    ports:
        - '4000:4000'

volumes:
  prometheus_data: {}
  grafana_data: {}