# global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'collect-node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'collect-api-metrics'
    static_configs:
      - targets: ['example-web-api:4000']
